### ISSUE TITLE
Co-Evolution of Evars

### ISSUE THREAD

**Issue by herbelin** [coq/ceps#13]
Let me start the discussion...

I like a lot your idea, as emphasized in Examples 1 and 2. It looks to me very natural and it is not without reminding me some theoretical issues raised by the introduction of `fun` patterns, as well as similar co-evolution of "match" typing that we can find in Jaber, Lewertowski, Pédrot, Sozeau and Tabareau's recent [paper](https://hal-mines-nantes.archives-ouvertes.fr/hal-01319066v1) on call-by-name forcing in type theory.

This does not seem unrelated either to the invertibility of negative rules as emphasized in calculi with focusing, namely that "destruct" (even in the case of more-than-2-constructors inductive types) is a rule of rearrangement of the context (see e.g. the use of disjunctive patterns destructing the context in Zeilberger or Munch-Maccagnoni's works, to cite names I know).

On the opposite side, I'm less convinced by Example 3 but I will think more at it [this paragraph has been edited afterwards].

On the implementation side, there are several directions possible. Personally, I'm used with ML programming so I would lean to suggest to add a line for co-evolution of evars somewhere in `Tactics.apply_induction_in_context` or so, but maybe this can be tried with less efforts in Ltac or MetaCoq.

**Comment by SkySkimmer** [comment]
This lacks context so I can't tell what it refers to.
